# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a=np.random.random(size=(2,3,5))
a

array([[[0.92793031, 0.1686559 , 0.02456676, 0.32124672, 0.50224933],
        [0.30523033, 0.52741406, 0.96025758, 0.76637816, 0.57054982],
        [0.20163958, 0.34261847, 0.58096039, 0.89868164, 0.9976183 ]],

       [[0.26394711, 0.50373627, 0.45669896, 0.22539142, 0.59737341],
        [0.77513905, 0.62752443, 0.30052417, 0.47706185, 0.04565263],
        [0.29618915, 0.27090248, 0.99158882, 0.46847726, 0.30004867]]])

In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.92793031 0.1686559  0.02456676 0.32124672 0.50224933]
  [0.30523033 0.52741406 0.96025758 0.76637816 0.57054982]
  [0.20163958 0.34261847 0.58096039 0.89868164 0.9976183 ]]

 [[0.26394711 0.50373627 0.45669896 0.22539142 0.59737341]
  [0.77513905 0.62752443 0.30052417 0.47706185 0.04565263]
  [0.29618915 0.27090248 0.99158882 0.46847726 0.30004867]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b=np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.shape)
print(b.shape)


(2, 3, 5)
(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?



In [10]:
# your answer here
#WE need to reshape them so they have the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c=b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d=a + c
d

#it works because the arrays have the same shape now

array([[[1.92793031, 1.1686559 , 1.02456676, 1.32124672, 1.50224933],
        [1.30523033, 1.52741406, 1.96025758, 1.76637816, 1.57054982],
        [1.20163958, 1.34261847, 1.58096039, 1.89868164, 1.9976183 ]],

       [[1.26394711, 1.50373627, 1.45669896, 1.22539142, 1.59737341],
        [1.77513905, 1.62752443, 1.30052417, 1.47706185, 1.04565263],
        [1.29618915, 1.27090248, 1.99158882, 1.46847726, 1.30004867]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)

#the difference is the value one, coming from the table c. From the addition of the two arrays

[[[0.92793031 0.1686559  0.02456676 0.32124672 0.50224933]
  [0.30523033 0.52741406 0.96025758 0.76637816 0.57054982]
  [0.20163958 0.34261847 0.58096039 0.89868164 0.9976183 ]]

 [[0.26394711 0.50373627 0.45669896 0.22539142 0.59737341]
  [0.77513905 0.62752443 0.30052417 0.47706185 0.04565263]
  [0.29618915 0.27090248 0.99158882 0.46847726 0.30004867]]]
[[[1.92793031 1.1686559  1.02456676 1.32124672 1.50224933]
  [1.30523033 1.52741406 1.96025758 1.76637816 1.57054982]
  [1.20163958 1.34261847 1.58096039 1.89868164 1.9976183 ]]

 [[1.26394711 1.50373627 1.45669896 1.22539142 1.59737341]
  [1.77513905 1.62752443 1.30052417 1.47706185 1.04565263]
  [1.29618915 1.27090248 1.99158882 1.46847726 1.30004867]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a*c
print(e)

[[[0.92793031 0.1686559  0.02456676 0.32124672 0.50224933]
  [0.30523033 0.52741406 0.96025758 0.76637816 0.57054982]
  [0.20163958 0.34261847 0.58096039 0.89868164 0.9976183 ]]

 [[0.26394711 0.50373627 0.45669896 0.22539142 0.59737341]
  [0.77513905 0.62752443 0.30052417 0.47706185 0.04565263]
  [0.29618915 0.27090248 0.99158882 0.46847726 0.30004867]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
#yes, because the values of a were multitplied by 1, which are the values of c

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max=d.max()
print(d_max)
d_min=d.min()
print(d_min)
d_mean=d.mean()
print(d_mean)

1.9976183047175762
1.0245667641278469
1.4898751017950311


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f=np.empty((2,3,5))
print(f)

[[[0.92793031 0.1686559  0.02456676 0.32124672 0.50224933]
  [0.30523033 0.52741406 0.96025758 0.76637816 0.57054982]
  [0.20163958 0.34261847 0.58096039 0.89868164 0.9976183 ]]

 [[0.26394711 0.50373627 0.45669896 0.22539142 0.59737341]
  [0.77513905 0.62752443 0.30052417 0.47706185 0.04565263]
  [0.29618915 0.27090248 0.99158882 0.46847726 0.30004867]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
grp,row,col=f.shape

for i in range(0,grp):
    for j in range(0,row):
        for z in range(0,col):
            #print(d[i,j,z])
            if (d[i,j,z] > d_min) & (d[i,j,z] < d_mean):
                f[i,j,z] = 25
            elif (d[i,j,z] > d_mean) & (d[i,j,z] < d_max):
                f[i,j,z] = 75
            elif d[i,j,z] == d_mean:
                f[i,j,z] = 50
            elif d[i,j,z] == d_min:
                f[i,j,z] = 0
            elif d[i,j,z] == d_max:
                f[i,j,z] = 100

print(d)
print(f)
# 1.9908695280774955
# 1.5455441312258502



[[[1.92793031 1.1686559  1.02456676 1.32124672 1.50224933]
  [1.30523033 1.52741406 1.96025758 1.76637816 1.57054982]
  [1.20163958 1.34261847 1.58096039 1.89868164 1.9976183 ]]

 [[1.26394711 1.50373627 1.45669896 1.22539142 1.59737341]
  [1.77513905 1.62752443 1.30052417 1.47706185 1.04565263]
  [1.29618915 1.27090248 1.99158882 1.46847726 1.30004867]]]
[[[ 75.  25.   0.  25.  75.]
  [ 25.  75.  75.  75.  75.]
  [ 25.  25.  75.  75. 100.]]

 [[ 25.  75.  25.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print(f)

[[[1.92793031 1.1686559  1.02456676 1.32124672 1.50224933]
  [1.30523033 1.52741406 1.96025758 1.76637816 1.57054982]
  [1.20163958 1.34261847 1.58096039 1.89868164 1.9976183 ]]

 [[1.26394711 1.50373627 1.45669896 1.22539142 1.59737341]
  [1.77513905 1.62752443 1.30052417 1.47706185 1.04565263]
  [1.29618915 1.27090248 1.99158882 1.46847726 1.30004867]]]
[[[ 75.  25.   0.  25.  75.]
  [ 25.  75.  75.  75.  75.]
  [ 25.  25.  75.  75. 100.]]

 [[ 25.  75.  25.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [22]:
# your code here

from numpy import dtype


f = np.array(f, dtype=object)

grp,row,col=f.shape

for i in range(0,grp):
    for j in range(0,row):
        for z in range(0,col):
            #print(d[i,j,z])
            if (d[i,j,z] > d_min) & (d[i,j,z] < d_mean):
                f[i,j,z] = "A"
            elif (d[i,j,z] > d_mean) & (d[i,j,z] < d_max):
                f[i,j,z] = "B"
            elif d[i,j,z] == d_mean:
                f[i,j,z] = "C"
            elif d[i,j,z] == d_min:
                f[i,j,z] = "D"
            elif d[i,j,z] == d_max:
                f[i,j,z] = "E"

print(d)
print(f)

[[[1.92793031 1.1686559  1.02456676 1.32124672 1.50224933]
  [1.30523033 1.52741406 1.96025758 1.76637816 1.57054982]
  [1.20163958 1.34261847 1.58096039 1.89868164 1.9976183 ]]

 [[1.26394711 1.50373627 1.45669896 1.22539142 1.59737341]
  [1.77513905 1.62752443 1.30052417 1.47706185 1.04565263]
  [1.29618915 1.27090248 1.99158882 1.46847726 1.30004867]]]
[[['B' 'A' 'D' 'A' 'B']
  ['A' 'B' 'B' 'B' 'B']
  ['A' 'A' 'B' 'B' 'E']]

 [['A' 'B' 'A' 'A' 'B']
  ['B' 'B' 'A' 'A' 'A']
  ['A' 'A' 'B' 'A' 'A']]]
